<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "vmec_churches"
 *
 * Auto generated by Extension Builder 2014-05-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Church directory',
	'description' => 'A simple directory of churches for TYPO3 CMS.',
	'category' => 'plugin',
	'author' => 'Christoph Fischer',
	'author_email' => 'christoph.fischer@volksmission.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);